# Generated by Django 3.1.1 on 2021-01-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('RNI', 'Rejected without interview'), ('INT', 'Invite to interview'), ('RWI', 'Rejected after interview'), ('OFS', 'Offer sent'), ('OFR', 'Offer rejected'), ('OFA', 'Offer accepted')], default='SUB', max_length=3),
        ),
    ]
