# Generated by Django 3.1.1 on 2020-12-31 19:46

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email_address', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('student_id', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('first_choice', models.CharField(blank=True, max_length=1000, null=True)),
                ('second_choice', models.CharField(blank=True, max_length=1000, null=True)),
                ('third_choice', models.CharField(blank=True, max_length=1000, null=True)),
                ('resume_link', models.CharField(blank=True, max_length=200, null=True)),
                ('general_question', models.CharField(blank=True, max_length=2000, null=True)),
                ('_skills', models.JSONField(default=students.models.get_default_skills)),
            ],
        ),
    ]
