# Generated by Django 3.1.1 on 2021-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(choices=[('L&S', 'College of Letters & Sciences'), ('COE', 'College of Engineering'), ('COC', 'College of Chemistry'), ('CED', 'College of Environmental Design'), ('CNR', 'Rausser College of Natural Resources'), ('HAAS', 'Haas School of Business')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('SP21', 'Spring 2021'), ('FA21', 'Fall 2021'), ('SP22', 'Spring 2022'), ('FA22', 'Fall 2022'), ('SP23', 'Spring 2023'), ('FA23', 'Fall 2023'), ('SP24', 'Spring 2024'), ('FA24', 'Fall 2024'), ('SP25', 'Spring 2025')], max_length=4),
        ),
    ]
