# Generated by Django 3.1.1 on 2021-01-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210101_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='general_question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
