# Generated by Django 3.1.1 on 2021-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210106_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='additional_skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
