# Generated by Django 3.1.1 on 2021-01-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_additional_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScholar',
            fields=[
                ('email_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
