# Generated by Django 3.1.1 on 2021-01-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_datascholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='general_question',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
