# Generated by Django 3.1.1 on 2021-01-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210114_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional_skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
