# Generated by Django 3.1.1 on 2021-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210116_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional_skills',
            field=models.CharField(blank=True, max_length=1100, null=True),
        ),
    ]
