# Generated by Django 3.1.5 on 2021-02-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20210118_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FA20', 'Fall 2020'), ('SP21', 'Spring 2021'), ('FA21', 'Fall 2021'), ('SP22', 'Spring 2022'), ('FA22', 'Fall 2022'), ('SP23', 'Spring 2023'), ('FA23', 'Fall 2023'), ('SP24', 'Spring 2024'), ('FA24', 'Fall 2024'), ('SP25', 'Spring 2025')], max_length=4),
        ),
    ]
