# Generated by Django 3.1.1 on 2020-12-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_num',
        ),
    ]
