# Generated by Django 3.1.1 on 2021-01-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210106_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dataset',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverable',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='project_workflow',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='skillset',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
