# Generated by Django 3.1.1 on 2021-01-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210106_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization_description',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
