# Generated by Django 3.1.1 on 2021-01-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210107_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skillset',
        ),
    ]
