# Generated by Django 3.1.1 on 2021-01-08 05:31

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_skillset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skillset',
            field=models.JSONField(default=projects.models.get_default_skills),
        ),
    ]
