# Generated by Django 3.1.1 on 2021-01-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210108_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deliverable',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
