# Generated by Django 3.1.5 on 2021-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210204_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='embed_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
