# Generated by Django 3.1.5 on 2021-03-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='marketing_channel',
            field=models.CharField(blank=True, choices=[('a', 'We reached out to you'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_marketing_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
