# Generated by Django 3.1.2 on 2021-03-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_embed_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProjCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.TextField()),
            ],
        ),
    ]
