# Generated by Django 3.1.2 on 2021-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_partnerprojcreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprojcreation',
            name='organization',
        ),
        migrations.AddField(
            model_name='partnerprojcreation',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerprojcreation',
            name='how_did_you_hear_about_us',
            field=models.CharField(choices=[('a', 'We reached out to you'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='partnerprojcreation',
            name='organization_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='partnerprojcreation',
            name='organization_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerprojcreation',
            name='organization_website',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='partnerprojcreation',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerprojcreation',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
