# Generated by Django 3.1.5 on 2021-03-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210306_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloud_creds',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dataset_availability',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='environment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hce_intern',
            field=models.CharField(blank=True, choices=[('a', 'Yes'), ('b', 'No'), ('c', 'Maybe')], max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='meet_regularly',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='num_students',
            field=models.CharField(choices=[('a', '3'), ('b', '4'), ('c', '5'), ('d', 'Other')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='optional_q1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='optional_q2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='optional_q3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_num_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_project_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='survey_response',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='marketing_channel',
            field=models.CharField(blank=True, choices=[('a', 'We reached out to you!'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='technical_requirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
