# Generated by Django 3.1.2 on 2021-03-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_project_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='marketing_channel',
            field=models.CharField(blank=True, choices=[('a', 'We reached out to you!'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], max_length=1),
        ),
    ]
