# Generated by Django 3.1.2 on 2021-03-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210303_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerProjCreation',
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='first_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='how_did_you_hear_about_us',
            field=models.CharField(choices=[('a', 'We reached out to you'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], default='DEFAULT VALUE', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='last_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='organization_website',
            field=models.URLField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization_description',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=1500),
        ),
    ]
