# Generated by Django 3.1.2 on 2021-03-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210303_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization_description',
            field=models.TextField(blank=True, default='DEFAULT VALUE'),
        ),
    ]
