# Generated by Django 3.1.5 on 2021-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210531_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
