# Generated by Django 3.1.5 on 2021-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210531_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('FA20', 'Fall 2020'), ('SP21', 'Spring 2021'), ('FA21', 'Fall 2021'), ('SP22', 'Spring 2022'), ('FA22', 'Fall 2022'), ('SP23', 'Spring 2023'), ('FA23', 'Fall 2023'), ('SP24', 'Spring 2024'), ('FA24', 'Fall 2024'), ('SP25', 'Spring 2025')], max_length=10),
        ),
    ]
