# Generated by Django 3.2 on 2021-06-28 00:51

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skillset',
            field=models.JSONField(blank=True, default=projects.models.get_default_skills, null=True),
        ),
    ]
