# Generated by Django 3.1.2 on 2021-03-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210307_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_students',
            field=models.CharField(blank='Select One', choices=[('a', '3'), ('b', '4'), ('c', '5'), ('d', 'Other')], max_length=1),
        ),
    ]
