# Generated by Django 3.1.5 on 2021-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20210531_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hce_intern',
            field=models.CharField(blank=True, choices=[('a', 'Yes'), ('b', 'No'), ('c', 'Maybe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_students',
            field=models.CharField(choices=[('a', '3'), ('b', '4'), ('c', '5'), ('d', 'Other')], default='a', max_length=20),
        ),
    ]
