# Generated by Django 3.1.2 on 2021-03-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_num_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_num_students',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_students',
            field=models.CharField(choices=[('a', '3'), ('b', '4'), ('c', '5'), ('d', 'Other')], default='a', max_length=1),
        ),
    ]
