# Generated by Django 3.1.5 on 2021-05-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20210531_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='marketing_channel',
            field=models.CharField(blank=True, choices=[('a', 'We reached out to you!'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], max_length=50),
        ),
    ]
