# Generated by Django 3.2 on 2021-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(blank=True, choices=[('a', 'Academia'), ('b', 'Social Sector'), ('c', 'Startup'), ('d', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
