# Generated by Django 3.1.2 on 2021-03-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210307_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='optional_q1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='optional_q2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='optional_q3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
