# Generated by Django 3.2 on 2021-06-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210531_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dataset',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='hce_intern',
            field=models.CharField(blank=True, choices=[('a', 'Yes'), ('b', 'No'), ('c', 'Maybe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='marketing_channel',
            field=models.CharField(blank=True, choices=[('a', 'We reached out to you!'), ('b', 'Through a reference'), ('c', 'Social media'), ('d', 'Our website'), ('e', 'Prior participation'), ('f', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_students',
            field=models.CharField(choices=[('a', '3'), ('b', '4'), ('c', '5'), ('d', 'Other')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.CharField(choices=[('FA20', 'Fall 2020'), ('SP21', 'Spring 2021'), ('FA21', 'Fall 2021'), ('SP22', 'Spring 2022'), ('FA22', 'Fall 2022'), ('SP23', 'Spring 2023'), ('FA23', 'Fall 2023'), ('SP24', 'Spring 2024'), ('FA24', 'Fall 2024'), ('SP25', 'Spring 2025')], max_length=4),
        ),
    ]
