# Generated by Django 3.1.1 on 2022-04-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20220411_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
