from django.db import models

from projects.models import Project


class Application(models.Model):

    # primary key auto-generated by project model
    student = models.ForeignKey("students.Student", on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    # rank of each applied project
    rank = models.IntegerField(default=0)

    status = models.CharField(max_length=100)

    def __str__(self):
        return self.student.email_address + " application for " + self.project.project_name
