from django.db import models
from students.models import Student
from projects.models import Project
# from students.models import tempApplication
# Create your models here.
class Application(models.Model):
    #email_address = models.EmailField(max_length=100, primary_key=True)
    #email_address = models.EmailField(max_length=100)

    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    # primary key auto-generated by project model
    #project_id = models.IntegerField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    # rank of each applied project
    rank = models.IntegerField(default=0)

    status = models.CharField(max_length=100)

    def __str__(self):
        return self.student.email_address + " application for " + self.project.project_name