# Generated by Django 3.1.1 on 2020-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('first_choice', models.CharField(max_length=1000)),
                ('second_choice', models.CharField(max_length=1000)),
                ('third_choice', models.CharField(max_length=1000)),
            ],
        ),
    ]
