# Generated by Django 3.1.1 on 2020-09-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('first_choice', models.CharField(max_length=50)),
                ('second_choice', models.CharField(max_length=50)),
                ('third_choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
