# Generated by Django 3.1.1 on 2020-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_choice',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='second_choice',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='third_choice',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
