# Generated by Django 3.1.1 on 2020-12-18 02:28

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_skills',
            field=models.JSONField(default=students.models.get_default_skills),
        ),
    ]
