# Generated by Django 3.1.1 on 2020-11-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201107_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_choice',
        ),
        migrations.RemoveField(
            model_name='student',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='student',
            name='third_choice',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
