# Generated by Django 3.1.1 on 2020-09-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_choice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_choice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_choice',
            field=models.CharField(max_length=100),
        ),
    ]
