# Generated by Django 3.1.1 on 2020-11-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
