# Generated by Django 3.1.1 on 2020-09-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200911_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_choice',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_choice',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='third_choice',
            field=models.CharField(max_length=1000),
        ),
    ]
