# Generated by Django 3.1.1 on 2020-09-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200911_2039'),
        ('students', '0007_auto_20200911_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_text',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='project_name',
            field=models.ForeignKey(default='404', on_delete=django.db.models.deletion.CASCADE, to='projects.partner'),
        ),
    ]
