# Generated by Django 3.1.1 on 2020-09-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200922_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='project_name',
            new_name='partner',
        ),
    ]
