# Generated by Django 3.1.1 on 2020-09-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200922_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(default='404', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
