# Generated by Django 3.1.1 on 2020-09-23 17:47

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_answer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=students.models.Question.create_id, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_address',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
