# Generated by Django 3.1.1 on 2020-09-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200923_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=3741694272257489863, max_length=200, primary_key=True, serialize=False),
        ),
    ]
