# Generated by Django 3.1.1 on 2020-09-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200928_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=5053677544722509516, max_length=200, primary_key=True, serialize=False),
        ),
    ]
