# Generated by Django 3.1.1 on 2020-09-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20200929_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=-6830984600941363293, max_length=200, primary_key=True, serialize=False),
        ),
    ]
