# Generated by Django 3.1.1 on 2020-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200929_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=-7162598057599515708, max_length=200, primary_key=True, serialize=False),
        ),
    ]
