# Generated by Django 3.1.1 on 2020-11-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('email_address', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
