# Generated by Django 3.1.1 on 2020-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('project_category', models.CharField(max_length=100)),
                ('student_num', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
