# Generated by Django 3.1.1 on 2020-09-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='has_data',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='hear_from',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='preferred_name',
        ),
    ]
