# Generated by Django 3.1.1 on 2020-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='id',
        ),
        migrations.AlterField(
            model_name='partner',
            name='email_address',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='partner',
            name='projects',
        ),
        migrations.AddField(
            model_name='partner',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
