# Generated by Django 3.1.1 on 2020-12-03 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('mc', 'multiple choice'), ('dropdown', 'dropdown'), ('checkbox', 'checkbox'), ('multiselect', 'multiselect'), ('range', 'range')], default='text', max_length=50),
        ),
        migrations.CreateModel(
            name='PartnerProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.partner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
