# Generated by Django 3.1.1 on 2020-09-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_answer_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
