# Generated by Django 3.1.1 on 2020-09-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200906_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='project_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
    ]
