# Generated by Django 3.1.1 on 2020-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200911_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='project_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
