# Generated by Django 3.1.1 on 2020-09-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200911_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
