# Generated by Django 3.1.1 on 2020-09-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200911_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='project_category',
            field=models.CharField(max_length=100),
        ),
    ]
