# Generated by Django 3.1.5 on 2021-01-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('SP21', 'Spring 2021'), ('FA21', 'Fall 2021'), ('SP22', 'Spring 2022'), ('FA22', 'Fall 2022'), ('SP23', 'Spring 2023'), ('FA23', 'Fall 2023'), ('SP24', 'Spring 2024'), ('FA24', 'Fall 2024'), ('SP25', 'Spring 2025')], max_length=4)),
                ('project_category', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=5000)),
                ('organization_description', models.CharField(blank=True, max_length=1500)),
                ('deliverable', models.CharField(blank=True, max_length=1000)),
                ('skillset', models.JSONField()),
                ('additional_skills', models.CharField(blank=True, max_length=500)),
                ('technical_requirements', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='APartner',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(to='archive.AProject')),
            ],
        ),
    ]
