# Generated by Django 3.1.5 on 2021-01-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APartner',
        ),
        migrations.DeleteModel(
            name='AProject',
        ),
    ]
