# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ staging, prod ]
  pull_request:
    branches: [ staging, prod ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      WEBDRIVER: ./google-chrome-stable_current_amd64.deb
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Google Chrome
      run: |
       chmod +x ./InstallChrome.sh
        ./InstallChrome.sh
        
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install -r requirements.txt
        
    - name: Run pytest
      run: |
        $CONDA/bin/coverage run manage.py test

    - name: Upload coverage
      run: |
        $CONDA/bin/codecov
